# Site settings
title: ChrisCheng
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is a studying blog created for Github
# baseurl: "/clean" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ChrisCheng1987
github_username:  ChrisCheng1987

# Build settings
markdown: kramdown
